import { Snippet } from './types';

const k = { color: '#C586C0' };
const t = { color: '#4EC9B0' };
const f = { color: '#DCDCAA' };
const s = { color: '#CE9178' };

const n = { color: '#B5CEA8' };
const v = { color: '#9CDCFE' };
const o = { color: '#D4D4D4' };
const p = { color: '#D7BA7D' };
const b = { color: '#569CD6' };

export const SNIPPETS: Record<string, Snippet> = {
  typescript: {
    language: 'TypeScript',
    filename: 'users.service.ts',
    lines: [
      { tokens: [{ text: 'interface ', ...b }, { text: 'User ', ...t }, { text: '{', ...o }] },
      { tokens: [{ text: '  id: ', ...o }, { text: 'string', ...t }, { text: ';', ...o }] },
      { tokens: [{ text: '  name: ', ...o }, { text: 'string', ...t }, { text: ';', ...o }] },
      { tokens: [{ text: '  email: ', ...o }, { text: 'string', ...t }, { text: ';', ...o }] },
      { tokens: [{ text: '  role: ', ...o }, { text: "'admin'", ...s }, { text: ' | ', ...o }, { text: "'user'", ...s }, { text: ';', ...o }] },
      { tokens: [{ text: '}', ...o }] },
      { tokens: [{ text: '' }] },
      { tokens: [{ text: 'const ', ...k }, { text: 'fetchUser', ...f }, { text: ' = ', ...o }, { text: 'async', ...k }, { text: ' (', ...o }, { text: 'id', ...p }, { text: ': ', ...o }, { text: 'string', ...t }, { text: '): ', ...o }, { text: 'Promise', ...t }, { text: '<', ...o }, { text: 'User', ...t }, { text: ' | ', ...o }, { text: 'null', ...t }, { text: '> => ', ...o }, { text: '{', ...o }] },
      { tokens: [{ text: '  const ', ...k }, { text: '{ data }', ...v }, { text: ' = ', ...o }, { text: 'await', ...k }, { text: ' api', ...v }, { text: '.from(', ...o }, { text: "'users'", ...s }, { text: ')', ...o }] },
      { tokens: [{ text: '    .select(', ...o }, { text: "'*'", ...s }, { text: ')', ...o }] },
      { tokens: [{ text: '    .eq(', ...o }, { text: "'id'", ...s }, { text: ', ', ...o }, { text: 'id', ...p }, { text: ')', ...o }] },
      { tokens: [{ text: '    .single()', ...v }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '  ', ...k }, { text: 'if', ...k }, { text: ' (!data) ', ...o }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'null', ...k }, { text: ';', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '  console.log(', ...v }, { text: '`User found: ', ...s }, { text: '${data.name}', ...v }, { text: '`', ...s }, { text: ');', ...o }] },
      { tokens: [{ text: '  ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'parseUser', ...f }, { text: '(data);', ...o }] },
      { tokens: [{ text: '}', ...o }] },
    ],
  },
  python: {
    language: 'Python',
    filename: 'routes/users.py',
    lines: [
      { tokens: [{ text: '@router.get(', ...f }, { text: '"/api/users/{user_id}"', ...s }, { text: ')', ...f }] },
      { tokens: [{ text: 'async ', ...k }, { text: 'def ', ...k }, { text: 'get_user', ...f }, { text: '(', ...o }] },
      { tokens: [{ text: '    user_id: ', ...p }, { text: 'str', ...t }, { text: ',', ...o }] },
      { tokens: [{ text: '    db: ', ...p }, { text: 'Database', ...t }, { text: ' = ', ...o }, { text: 'Depends', ...t }, { text: '(get_db)', ...o }] },
      { tokens: [{ text: ') -> ', ...o }, { text: 'User', ...t }, { text: ':', ...o }] },
      { tokens: [{ text: '    query = ', ...o }, { text: '"""', ...s }] },
      { tokens: [{ text: '        SELECT id, name, email, role', ...s }] },
      { tokens: [{ text: '        FROM users', ...s }] },
      { tokens: [{ text: '        WHERE id = :user_id', ...s }] },
      { tokens: [{ text: '    """', ...s }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    result = await db.fetch_one(', ...v }] },
      { tokens: [{ text: '        query, ', ...v }, { text: '{"user_id": user_id}', ...n }, { text: ')', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    ', ...k }, { text: 'if', ...k }, { text: ' result is ', ...o }, { text: 'None', ...k }, { text: ':', ...o }] },
      { tokens: [{ text: '        raise ', ...k }, { text: 'HTTPException', ...t }, { text: '(', ...o }] },
      { tokens: [{ text: '            status_code=', ...v }, { text: '404', ...n }, { text: ',', ...o }] },
      { tokens: [{ text: '            detail=', ...v }, { text: '"User not found"', ...s }, { text: ',', ...o }] },
      { tokens: [{ text: '        )', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'User', ...t }, { text: '(**result._mapping)', ...o }] },
    ],
  },
  dart: {
    language: 'Dart',
    filename: 'repositories/user_repository.dart',
    lines: [
      { tokens: [{ text: 'class ', ...b }, { text: 'UserRepository ', ...t }, { text: '{', ...o }] },
      { tokens: [{ text: '  final Dio _client;', ...v }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '  ', ...t }, { text: 'UserRepository', ...f }, { text: '(this._client);', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '  Future', ...t }, { text: '<', ...o }, { text: 'User?> ', ...t }, { text: 'getUser', ...f }, { text: '(', ...o }, { text: 'String', ...t }, { text: ' id', ...p }, { text: ') ', ...o }, { text: 'async', ...k }, { text: ' {', ...o }] },
      { tokens: [{ text: '    ', ...k }, { text: 'try', ...k }, { text: ' {', ...o }] },
      { tokens: [{ text: '      final response = await _client.get(', ...v }] },
      { tokens: [{ text: "        '/users/$id',", ...s }] },
      { tokens: [{ text: '        queryParameters: ', ...v }, { text: '{\'include\': \'projects\'}', ...n }, { text: ',', ...o }] },
      { tokens: [{ text: '      );', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '      ', ...k }, { text: 'if', ...k }, { text: ' (response.statusCode == ', ...n }, { text: '200', ...n }, { text: ') {', ...o }] },
      { tokens: [{ text: '        ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'User', ...t }, { text: '.fromJson(', ...f }, { text: 'response.data', ...v }, { text: ');', ...o }] },
      { tokens: [{ text: '      }', ...o }] },
      { tokens: [{ text: '    } ', ...k }, { text: 'on', ...k }, { text: ' ', ...t }, { text: 'DioException', ...t }, { text: ' ', ...k }, { text: 'catch', ...k }, { text: ' (e) {', ...o }] },
      { tokens: [{ text: '      log(', ...v }, { text: "'Error fetching user: $e'", ...s }, { text: ');', ...o }] },
      { tokens: [{ text: '    }', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'null', ...k }, { text: ';', ...o }] },
      { tokens: [{ text: '  }', ...o }] },
      { tokens: [{ text: '}', ...o }] },
    ],
  },
  csharp: {
    language: 'C#',
    filename: 'Controllers/UsersController.cs',
    lines: [
      { tokens: [{ text: '[ApiController]', ...f }] },
      { tokens: [{ text: '[Route(', ...f }, { text: '"api/[controller]"', ...s }, { text: ')]', ...f }] },
      { tokens: [{ text: 'public ', ...k }, { text: 'class ', ...k }, { text: 'UsersController', ...t }, { text: ' : ', ...o }, { text: 'ControllerBase', ...t }, { text: '', ...o }, { text: '{', ...o }] },
      { tokens: [{ text: '    private readonly AppDbContext _db;', ...v }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    ', ...k }, { text: 'public ', ...k }, { text: 'UsersController', ...f }, { text: '(', ...o }, { text: 'AppDbContext', ...t }, { text: ' db', ...p }, { text: ')', ...o }] },
      { tokens: [{ text: '    {', ...o }] },
      { tokens: [{ text: '        _db = db;', ...o }] },
      { tokens: [{ text: '    }', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '    [HttpGet("{id}")]', ...f }] },
      { tokens: [{ text: '    ', ...k }, { text: 'public ', ...k }, { text: 'async ', ...k }, { text: 'Task', ...t }, { text: '<', ...o }, { text: 'ActionResult', ...t }, { text: '<', ...o }, { text: 'UserDto', ...t }, { text: '>> ', ...o }, { text: 'GetUser', ...f }, { text: '(', ...o }] },
      { tokens: [{ text: '        string id,', ...p }] },
      { tokens: [{ text: '        CancellationToken ct', ...t }] },
      { tokens: [{ text: '    )', ...o }] },
      { tokens: [{ text: '    {', ...o }] },
      { tokens: [{ text: '        var user = await _db.Users', ...v }] },
      { tokens: [{ text: '            .AsNoTracking()', ...v }] },
      { tokens: [{ text: '            .Include(u => u.Projects)', ...v }] },
      { tokens: [{ text: '            .FirstOrDefaultAsync(', ...f }] },
      { tokens: [{ text: '                u => u.Id == id, ct', ...p }] },
      { tokens: [{ text: '            );', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '        ', ...k }, { text: 'if', ...k }, { text: ' (user ', ...k }, { text: 'is', ...k }, { text: ' ', ...o }, { text: 'null', ...k }, { text: ')', ...o }] },
      { tokens: [{ text: '            ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'NotFound', ...f }, { text: '();', ...o }] },
      { tokens: [{ text: '', ...o }] },
      { tokens: [{ text: '        ', ...k }, { text: 'return', ...k }, { text: ' ', ...o }, { text: 'Ok', ...f }, { text: '(', ...o }, { text: 'UserDto', ...t }, { text: '.FromEntity(', ...f }, { text: 'user', ...p }, { text: '));', ...o }] },
      { tokens: [{ text: '    }', ...o }] },
      { tokens: [{ text: '}', ...o }] },
    ],
  },
};
